version: "3"
services:
  web:
    #docker image build -t demo:3.0 .
    image: demo:3.0
    build:
      context: ./example01
      dockerfile: Dockerfile
    #docker container run -d -p 9999:80 demo:1.0
    ports:
      - 9999:80

  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=day01
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql/1.sql:/docker-entrypoint-initdb.d/1.sql