version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  lb:
    build:
      context: ./loadbalance
      dockerfile: Dockerfile
    ports:
      - 8888:80
    depends_on:
      web:
        condition: service_healthy

  web:
    #docker image build -t demo:3.0 .
    image: demo:3.0
    environment:
      - PAYMENT_ENDPOINT=${URL:-http://dev.demo.com}
    build:
      context: ./example01
      dockerfile: Dockerfile
    #docker container run -d -p 9999:80 demo:1.0
    # ports:
    #   - 9999:80
    healthcheck:
      test: "curl --fail --silent localhost || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s


  admin:
    image: phpmyadmin
    ports:
      - 7777:80

  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=day01
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql/1.sql:/docker-entrypoint-initdb.d/1.sql