version: "3"
services:
  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=day01
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql/1.sql:/docker-entrypoint-initdb.d/1.sql